import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
import MittaAIAssistant from "./MittaAIAssistant";

export default function HomeDashboard() {
  return (
      <div className="min-h-screen bg-slate-100">

            <Navbar />

                  <div className="flex">

                          <Sidebar />

                                  <main className="flex-1 p-8">

                                            <div className="mb-8">
                                                        <h1 className="text-4xl font-bold text-slate-800">
                                                                      🎓 Welcome, Dhammadoot Mule Sir
                                                                                  </h1>

                                                                                              <p className="text-slate-500 mt-2">
                                                                                                            Your Personal AI Powered Learning Platform
                                                                                                                        </p>
                                                                                                                                  </div>

                                                                                                                                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">

                                                                                                                                                        <div className="bg-blue-600 text-white rounded-2xl p-6 shadow-lg">
                                                                                                                                                                      <h3 className="text-lg font-semibold">📚 Notes</h3>
                                                                                                                                                                                    <p className="text-3xl font-bold mt-4">245</p>
                                                                                                                                                                                                </div>

                                                                                                                                                                                                            <div className="bg-green-600 text-white rounded-2xl p-6 shadow-lg">
                                                                                                                                                                                                                          <h3 className="text-lg font-semibold">❓ Quiz</h3>
                                                                                                                                                                                                                                        <p className="text-3xl font-bold mt-4">1800+</p>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                <div className="bg-orange-600 text-white rounded-2xl p-6 shadow-lg">
                                                                                                                                                                                                                                                                              <h3 className="text-lg font-semibold">📄 PYQ</h3>
                                                                                                                                                                                                                                                                                            <p className="text-3xl font-bold mt-4">500+</p>
                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                    <div className="bg-purple-700 text-white rounded-2xl p-6 shadow-lg">
                                                                                                                                                                                                                                                                                                                                  <h3 className="text-lg font-semibold">🤖 MITTA AI</h3>
                                                                                                                                                                                                                                                                                                                                                <p className="text-lg mt-4">Always Ready</p>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-10 bg-white rounded-3xl shadow-xl p-8">

                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-2xl font-bold mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                          🚀 MITTA AI Assistant
                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-slate-600">
                                                                                                                                                                                                                                                                                                                                                                                                                                                Ask anything about MPSC, UPSC, Police Bharti,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Talathi, History, Geography, Science,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Economy and Current Affairs.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button className="mt-6 bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl font-semibold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Start Chat with MITTA AI
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <MittaAIAssistant />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }